import ReduxProvider from "@/app/_lib/ReduxProvider";
import { Montserrat } from "next/font/google";
import Header from "@/app/_components/Header";
import Footer from "@/app/_components/Footer";
import "./global.css";
import { Suspense } from "react";

const montserrat = Montserrat({
  style: ["normal"],
  display: "swap",
  subsets: ["latin"],
});

export const metadata = {
  title: {
    template: "%s / WhatBytes",
    default: "WhatBytes",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <ReduxProvider>
          <Suspense fallback={<p>Loading...</p>}>
            <Header />
          </Suspense>
          {children}
        </ReduxProvider>
        <Footer />
      </body>
    </html>
  );
}
